apiVersion: v1
kind: Service
metadata:
  name: recast-service
spec:
  selector:
    app: recast
    stage: prod
  ports:
    - port: 80
      targetPort: http
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: recast-autoscale
spec:
  scaleTargetRef:
    kind: Deployment
    name: recast-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: recast-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recast
      stage: prod
  revisionHistoryLimit: 5
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: recast
        stage: prod
    spec:
      containers:
      - name: recast
        image: kfengbest/mst-js-recast
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8080
        env:
        - name: VERSION
          value: v1.0.0
